### ISSUE TITLE
Bug: `TextButton`, `Button` 컴포넌트  as="a" 셋팅시, 마우스 hover 스타일 먹지 않음.

### ISSUE THREAD

**Issue by sungkwangkim** [wanteddev/montage-web#78]
### 요약

TextButton, Button 컴포넌트에서 as="a" 속성을 부여 했을때, 마우스 hover 스타일이 다름.

### 상세

아래와 같이 사용 했을때, 
hover 스타일이 제대로 나오지 않음.

```
import { TextButton, Button } from '@wanteddev/wds';

        <Button
            variant="solid"
            fullWidth
            size="large"
            as="a"
            target="_blank"
            href="https://www.wanted.co.kr/dashboard/ad/toppicks">
            상품 신청하기
          </Button>
          <TextButton as="a" target="_blank" href="https://ad.wantedlab.com/ad_home/toppicks">
              상품 상세설명 보기
          </TextButton>
```

### AS-IS

<img width="793" alt="스크린샷 2024-08-20 10 25 49" src="https://github.com/user-attachments/assets/954fef36-5aa9-4038-8d2c-bac8f3603e01">

<img width="870" alt="스크린샷 2024-08-20 10 25 55" src="https://github.com/user-attachments/assets/b03c2637-3270-4281-afde-d6da80383924">

**Comment by Sh031224** [comment]
@sungkwangkim 성광님 제가 확인해봤는데, 유저웹의 글로벌 스타일 때문에 다르게 적용되는 것 같아요!

```css
a {
  font-family: inherit;
  text-decoration: inherit;
  cursor: pointer;

  &,
  &:active,
  &:hover,
  &:visited {
    color: inherit;
  }
}
```
